### PR TITLE
Added "save" to newly updated transition entries

### PR DESCRIPTION
**Pull request by tianenchong**

### CODE REVIEW

**Comment by luca-della-vedova** [comment]
Thanks for the fix! Can you fix the style check?

**Comment by tianenchong** [comment]
I have no idea about style check. What is it about actually?

**Comment by luca-della-vedova** [comment]
It's about respecting the code style in the rmf codebase, if you click on "Details" you can see what the issue is and how it should be fixed.

**Comment by tianenchong** [comment]
`Run wget https://raw.githubusercontent.com/osrf/rmf_core/master/rmf_utils/test/format/rmf_code_style.cfg
--2020-11-27 03:13:53--  https://raw.githubusercontent.com/osrf/rmf_core/master/rmf_utils/test/format/rmf_code_style.cfg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.208.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.208.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 102281 (100K) [text/plain]
Saving to: ‘rmf_code_style.cfg’

     0K .......... .......... .......... .......... .......... 50% 4.48M 0s
    50K .......... .......... .......... .......... ......... 100% 4.50M=0.02s

2020-11-27 03:13:53 (4.49 MB/s) - ‘rmf_code_style.cfg’ saved [102281/102281]

No code style divergence in file 'building_sim_plugins/building_gazebo_plugins/src/crowd_simulator.cpp'

No code style divergence in file 'building_sim_plugins/building_gazebo_plugins/src/crowd_simulator.hpp'

No code style divergence in file 'building_sim_plugins/building_gazebo_plugins/src/door.cpp'

No code style divergence in file 'building_sim_plugins/building_gazebo_plugins/src/lift.cpp'

No code style divergence in file 'building_sim_plugins/building_gazebo_plugins/src/slotcar.cpp'

No code style divergence in file 'building_sim_plugins/building_gazebo_plugins/src/thumbnail_generator.cpp'

No code style divergence in file 'building_sim_plugins/building_gazebo_plugins/src/toggle_charging.cpp'

No code style divergence in file 'building_sim_plugins/building_gazebo_plugins/src/toggle_floors.cpp'

No code style divergence in file 'building_sim_plugins/building_ignition_plugins/src/crowd_simulator.cpp'

No code style divergence in file 'building_sim_plugins/building_ignition_plugins/src/crowd_simulator.hpp'

No code style divergence in file 'building_sim_plugins/building_ignition_plugins/src/door.cpp'

No code style divergence in file 'building_sim_plugins/building_ignition_plugins/src/lift.cpp'

No code style divergence in file 'building_sim_plugins/building_ignition_plugins/src/slotcar.cpp'

No code style divergence in file 'building_sim_plugins/building_ignition_plugins/src/toggle_charging/toggle_charging.cpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/include/building_sim_common/crowd_simulator_common.hpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/include/building_sim_common/door_common.hpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/include/building_sim_common/lift_common.hpp'
Code style divergence in file 'traffic_editor/gui/crowd_sim/transition_table.cpp':

--- traffic_editor/gui/crowd_sim/transition_table.cpp
+++ traffic_editor/gui/crowd_sim/transition_table.cpp.uncrustify
@@ -114 +114 @@
-    [this](const QString &text)
+    [this](const QString& text)

1 files with code style divergence

No code style divergence in file 'building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/include/building_sim_common/utils.hpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/src/crowd_simulator_common.cpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/src/door_common.cpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/src/lift_common.cpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/src/slotcar_common.cpp'

No code style divergence in file 'building_sim_plugins/building_plugins_common/src/utils.cpp'

No code style divergence in file 'traffic_editor/gui/add_param_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/add_param_dialog.h'

No code style divergence in file 'traffic_editor/gui/building.cpp'

No code style divergence in file 'traffic_editor/gui/building_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/building_dialog.h'

No code style divergence in file 'traffic_editor/gui/building_level.cpp'

No code style divergence in file 'traffic_editor/gui/building_level_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/building_level_dialog.h'

No code style divergence in file 'traffic_editor/gui/building_level_table.cpp'

No code style divergence in file 'traffic_editor/gui/building_level_table.h'

No code style divergence in file 'traffic_editor/gui/edge.cpp'

No code style divergence in file 'traffic_editor/gui/editor.cpp'

No code style divergence in file 'traffic_editor/gui/editor.h'

No code style divergence in file 'traffic_editor/gui/editor_mode_id.h'

No code style divergence in file 'traffic_editor/gui/editor_model.cpp'

No code style divergence in file 'traffic_editor/gui/fiducial.cpp'

No code style divergence in file 'traffic_editor/gui/layer.cpp'

No code style divergence in file 'traffic_editor/gui/layer_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/layer_dialog.h'

No code style divergence in file 'traffic_editor/gui/level.cpp'

No code style divergence in file 'traffic_editor/gui/lift.cpp'

No code style divergence in file 'traffic_editor/gui/lift_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/lift_dialog.h'

No code style divergence in file 'traffic_editor/gui/lift_door.cpp'

No code style divergence in file 'traffic_editor/gui/lift_table.cpp'

No code style divergence in file 'traffic_editor/gui/lift_table.h'

No code style divergence in file 'traffic_editor/gui/main.cpp'

No code style divergence in file 'traffic_editor/gui/map_view.cpp'

No code style divergence in file 'traffic_editor/gui/map_view.h'

No code style divergence in file 'traffic_editor/gui/model.cpp'

No code style divergence in file 'traffic_editor/gui/model_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/model_dialog.h'

No code style divergence in file 'traffic_editor/gui/multi_select_combo_box.cpp'

No code style divergence in file 'traffic_editor/gui/multi_select_combo_box.h'

No code style divergence in file 'traffic_editor/gui/param.cpp'

No code style divergence in file 'traffic_editor/gui/polygon.cpp'

No code style divergence in file 'traffic_editor/gui/preferences_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/preferences_dialog.h'

No code style divergence in file 'traffic_editor/gui/preferences_keys.cpp'

No code style divergence in file 'traffic_editor/gui/preferences_keys.h'

No code style divergence in file 'traffic_editor/gui/project.cpp'

No code style divergence in file 'traffic_editor/gui/project.h'

No code style divergence in file 'traffic_editor/gui/project_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/project_dialog.h'

No code style divergence in file 'traffic_editor/gui/scenario.cpp'

No code style divergence in file 'traffic_editor/gui/scenario.h'

No code style divergence in file 'traffic_editor/gui/scenario_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/scenario_dialog.h'

No code style divergence in file 'traffic_editor/gui/scenario_level.cpp'

No code style divergence in file 'traffic_editor/gui/scenario_level.h'

No code style divergence in file 'traffic_editor/gui/scenario_table.cpp'

No code style divergence in file 'traffic_editor/gui/scenario_table.h'

No code style divergence in file 'traffic_editor/gui/sim_thread.cpp'

No code style divergence in file 'traffic_editor/gui/sim_thread.h'

No code style divergence in file 'traffic_editor/gui/table_list.cpp'

No code style divergence in file 'traffic_editor/gui/table_list.h'

No code style divergence in file 'traffic_editor/gui/traffic_map.cpp'

No code style divergence in file 'traffic_editor/gui/traffic_map.h'

No code style divergence in file 'traffic_editor/gui/traffic_map_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/traffic_map_dialog.h'

No code style divergence in file 'traffic_editor/gui/traffic_table.cpp'

No code style divergence in file 'traffic_editor/gui/traffic_table.h'

No code style divergence in file 'traffic_editor/gui/vertex.cpp'

No code style divergence in file 'traffic_editor/gui/yaml_utils.cpp'

No code style divergence in file 'traffic_editor/gui/yaml_utils.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/agent_group.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/agent_group_table.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/agent_group_table.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/agent_profile.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/agent_profile_table.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/agent_profile_table.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/condition.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/condition_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/condition_dialog.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/crowd_sim_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/crowd_sim_dialog.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/crowd_sim_editor_table.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/crowd_sim_editor_table.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/crowd_sim_impl.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/crowd_sim_table_base.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/crowd_sim_table_base.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/goal_set.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/goal_set_table.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/goal_set_table.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/model_type.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/model_type_table.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/model_type_table.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/state.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/state_table.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/state_table.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/to_state_dialog.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/to_state_dialog.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/to_state_table.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/to_state_table.h'

No code style divergence in file 'traffic_editor/gui/crowd_sim/transition.cpp'

No code style divergence in file 'traffic_editor/gui/crowd_sim/transition_table.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/building.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/building_level.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/edge.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/editor_model.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/fiducial.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/layer.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/level.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/lift.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/lift_door.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/model.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/model_state.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/param.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/polygon.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/rendering_options.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/vertex.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/crowd_sim/agent_group.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/crowd_sim/agent_profile.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/crowd_sim/condition.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/crowd_sim/crowd_sim_impl.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/crowd_sim/goal_set.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/crowd_sim/model_type.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/crowd_sim/state.h'

No code style divergence in file 'traffic_editor/include/traffic_editor/crowd_sim/transition.h'

No code style divergence in file 'traffic_editor/plugins/simulation.h'

Error: Process completed with exit code 1.`

**Comment by tianenchong** [comment]
What does it mean by "no code style divergence" ?
[log.log](https://github.com/osrf/traffic_editor/files/5606169/log.log)

**Comment by luca-della-vedova** [comment]
> What does it mean by "no code style divergence" ?
> [log.log](https://github.com/osrf/traffic_editor/files/5606169/log.log)

There is a code divergence in a transition_table.cpp if you look carefully, that one is the cause of the error

**Comment by tianenchong** [comment]
oh, it's the placement.

**Comment by luca-della-vedova** [comment]
Also it seems your vscode file was included in the PR?

**Comment by tianenchong** [comment]
Shall I remove it?

**Review by luca-della-vedova — APPROVED** [review]
Works great, thanks for the fix!

**Pull request merged**
