### PR TITLE
speedup gz world

### PR DESCRIPTION
**Pull request by tanyouliang95**
Similar to this in ign: https://github.com/osrf/traffic_editor/pull/248, update default max stepsize to speedup gz sim world

### CODE REVIEW

**Comment by Briancbn** [comment]
I am actually configuring this myself through a post processing script, will it be better if this is make configurable through building_map_tools cli arguments? or better still in the yaml.

Just a suggestion.

**Comment by Yadunund** [comment]
I too feel this value should be configured by users after world generation as it is subjective to respective hardware configurations.

**Comment by tanyouliang95** [comment]
Since this is just a default value, users can still change it on the gazebo GUI side panel. Having a default just make it slightly convenient to launch and test directly in a speed up manner (reduce the number of clicks). Regardless, any suggestions in making it convenient would be fine.

**Comment by Briancbn** [comment]
> Since this is just a default value, users can still change it on the gazebo GUI side panel. Having a default just make it slightly convenient to launch and test directly in a speed up manner (reduce the number of clicks). Regardless, any suggestions in making it convenient would be fine.

Noted. Fair enough as well.

**Pull request closed without merging**
